package net.parostroj.timetable.gui.dialogs;

import java.awt.Frame;
import java.awt.Rectangle;
import javax.swing.JPanel;
import net.parostroj.timetable.gui.AppPreferences;
import net.parostroj.timetable.gui.StorableGuiData;
import net.parostroj.timetable.utils.ResourceLoader;

/**
 * Floating dialog window.
 *
 * @author jub
 */
public class FloatingDialog extends javax.swing.JDialog implements StorableGuiData {

    private String storageKeyPrefix;

    /** Creates new form FloatingDialog */
    public FloatingDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public FloatingDialog(Frame parent, JPanel panel, String titleKey, String storageKeyPrefix) {
        this(parent, false);
        this.setTitle(ResourceLoader.getString(titleKey));
        getContentPane().add(panel, java.awt.BorderLayout.CENTER);
        
        this.storageKeyPrefix = storageKeyPrefix;

        // update layout
        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String createStorageKey(String keySuffix) {
        return new StringBuilder(storageKeyPrefix).append('.').append(keySuffix).toString();
    }

    @Override
    public void saveToPreferences(AppPreferences prefs) {
        prefs.setInt(this.createStorageKey("x"), this.getX());
        prefs.setInt(this.createStorageKey("y"), this.getY());
        prefs.setInt(this.createStorageKey("width"), this.getWidth());
        prefs.setInt(this.createStorageKey("height"), this.getHeight());
        prefs.setBoolean(this.createStorageKey("visible"), this.isVisible());
    }

    @Override
    public void loadFromPreferences(AppPreferences prefs) {
        if ((prefs.getInt(this.createStorageKey("x")) == null) ||
                (prefs.getInt(this.createStorageKey("y")) == null) ||
                (prefs.getInt(this.createStorageKey("height")) == null) ||
                (prefs.getInt(this.createStorageKey("width")) == null)) {
            return;
        }
        Rectangle r = new Rectangle(
                prefs.getInt(this.createStorageKey("x")),
                prefs.getInt(this.createStorageKey("y")),
                prefs.getInt(this.createStorageKey("width")),
                prefs.getInt(this.createStorageKey("height")));
        // set position and size
        this.setBounds(r);
        // set visibility
        if (Boolean.TRUE.equals(prefs.getBoolean(this.createStorageKey("visible"))))
                this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
