package net.parostroj.timetable.gui.dialogs;

import java.awt.Frame;
import java.awt.Rectangle;
import java.util.LinkedList;
import java.util.List;
import java.util.StringTokenizer;
import javax.swing.JPanel;
import net.parostroj.timetable.gui.AppPreferences;
import net.parostroj.timetable.gui.StorableGuiData;
import net.parostroj.timetable.utils.ResourceLoader;

/**
 * Floating dialog window.
 *
 * @author jub
 */
public class FloatingDialog extends javax.swing.JDialog implements StorableGuiData {

    private String storageKeyPrefix;

    /** Creates new form FloatingDialog */
    public FloatingDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public FloatingDialog(Frame parent, JPanel panel, String titleKey, String storageKeyPrefix) {
        this(parent, false);
        this.setTitle(ResourceLoader.getString(titleKey));
        getContentPane().add(panel, java.awt.BorderLayout.CENTER);
        
        this.storageKeyPrefix = storageKeyPrefix;

        // update layout
        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String createStorageKey(String keySuffix) {
        return new StringBuilder(storageKeyPrefix).append('.').append(keySuffix).toString();
    }

    private List<Integer> parsePosition(String preferences) {
        StringTokenizer tokenizer = new StringTokenizer(preferences, "|");
        List<Integer> positions = new LinkedList<Integer>();
        while (tokenizer.hasMoreTokens()) {
            String token = tokenizer.nextToken();
            positions.add(Integer.valueOf(token));
        }
        return (positions.size() != 4) ? null : positions;
    }

    private String createPosition() {
        return String.format("%d|%d|%d|%d", this.getX(), this.getY(), this.getWidth(), this.getHeight());
    }

    @Override
    public void saveToPreferences(AppPreferences prefs) {
        prefs.removeWithPrefix(storageKeyPrefix);
        prefs.setString(this.createStorageKey("position"), this.createPosition());
        prefs.setBoolean(this.createStorageKey("visible"), this.isVisible());
    }

    @Override
    public void loadFromPreferences(AppPreferences prefs) {
        // set position
        String positionStr = prefs.getString(this.createStorageKey("position"));
        if (positionStr != null) {
            List<Integer> positions = this.parsePosition(positionStr);
            if (positions != null) {
                Rectangle r = new Rectangle(positions.get(0),
                        positions.get(1),
                        positions.get(2),
                        positions.get(3));
                this.setBounds(r);
            }
        }
        // set visibility
        if (Boolean.TRUE.equals(prefs.getBoolean(this.createStorageKey("visible"))))
                this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
