/*
 * EngineCyclesPane.java
 *
 * Created on 12. září 2007, 13:33
 */

package net.parostroj.timetable.gui.panes;

import java.awt.Color;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;
import net.parostroj.timetable.gui.ApplicationModel;
import net.parostroj.timetable.gui.ApplicationModelEvent;
import net.parostroj.timetable.gui.views.GraphicalTimetableView.TrainColors;
import net.parostroj.timetable.gui.views.HighlightedTrains;
import net.parostroj.timetable.gui.views.TCDelegate;
import net.parostroj.timetable.gui.views.TrainColorChooser;
import net.parostroj.timetable.model.Train;
import net.parostroj.timetable.model.TrainsCycle;
import net.parostroj.timetable.model.TrainsCycleItem;

/**
 * Pane for manipulating engine cycles.
 *
 * @author jub
 */
public class TrainsCyclesPane extends javax.swing.JPanel {
    
    /** Creates new form EngineCyclesPane */
    public TrainsCyclesPane() {
        initComponents();
    }
    
    public void setModel(ApplicationModel model, final TCDelegate delegate, TrainColorChooser chooser) {
        eCListView.setModel(model, delegate);
        eCDetailsView.setModel(model, delegate);
        eCTrainListView.setModel(model, delegate);
        graphicalTimetableView.setModel(model);
        graphicalTimetableView.setTrainColors(TrainColors.BY_COLOR_CHOOSER,chooser);

        HighlightedTrains ht = new HighlightedTrains() {
            
            private Set<Train> set = Collections.emptySet();
            
            private TrainsCycle last;

            @Override
            public Set<Train> getHighlighedTrains() {
                return set;
            }

            @Override
            public void modelChanged(ApplicationModelEvent event) {
                if (delegate.transformEventType(event.getType()) == TCDelegate.Action.SELECTED_CHANGED) {
                    last = delegate.getSelectedCycle(event.getModel());
                    set = this.createSet(last);
                    graphicalTimetableView.repaint();
                } else if (delegate.transformEventType(event.getType()) == TCDelegate.Action.MODIFIED_CYCLE) {
                    if (event.getObject() == last) {
                        set = this.createSet(last);
                        graphicalTimetableView.repaint();
                    }
                }
            }
            
            private Set<Train> createSet(TrainsCycle cycle) {
                if (cycle == null)
                    return Collections.emptySet();
                
                Set<Train> result = new HashSet<Train>();
                for (TrainsCycleItem item : cycle) {
                    result.add(item.getTrain());
                }
                return result;
            }

            @Override
            public Color getColor() {
                return Color.RED;
            }
        };
        model.addListener(ht);
        graphicalTimetableView.setHTrains(ht);
        graphicalTimetableView.setTrainSelector(eCTrainListView);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eCListView = new net.parostroj.timetable.gui.views.TCListView();
        eCDetailsView = new net.parostroj.timetable.gui.views.TCDetailsView2();
        eCTrainListView = new net.parostroj.timetable.gui.views.TCTrainListView();
        scrollPane = new javax.swing.JScrollPane();
        graphicalTimetableView = new net.parostroj.timetable.gui.views.GraphicalTimetableView();

        javax.swing.GroupLayout graphicalTimetableViewLayout = new javax.swing.GroupLayout(graphicalTimetableView);
        graphicalTimetableView.setLayout(graphicalTimetableViewLayout);
        graphicalTimetableViewLayout.setHorizontalGroup(
            graphicalTimetableViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4000, Short.MAX_VALUE)
        );
        graphicalTimetableViewLayout.setVerticalGroup(
            graphicalTimetableViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );

        scrollPane.setViewportView(graphicalTimetableView);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eCListView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(eCDetailsView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eCTrainListView, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(eCListView, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eCDetailsView, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(eCTrainListView, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private net.parostroj.timetable.gui.views.TCDetailsView2 eCDetailsView;
    private net.parostroj.timetable.gui.views.TCListView eCListView;
    private net.parostroj.timetable.gui.views.TCTrainListView eCTrainListView;
    private net.parostroj.timetable.gui.views.GraphicalTimetableView graphicalTimetableView;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
    
}
